#!/bin/sh
name=centos7
port=2346
wait_s=22

if [ -z "$1" ]; then
    if [ -z "$(ps -ef|grep "[abc]omment $name")" ]; then
        VBoxManage startvm "$name" --type headless
        echo ">>>>>>>>>>>>>>>>>>>>>>>>>> starting $name"
        sleep $wait_s
        ssh -p $port liren@127.0.0.1
    else
        ssh -p $port liren@127.0.0.1
    fi
elif [ "$1" = "p" ]; then
    if [ -n "$(ps -ef|grep -E "ca?omment $name")" ]; then
        echo ">>>>>>>>>>>>>>>>>>>>>>>>>> stopping $name"
        VBoxManage controlvm "$name" poweroff
    else
        echo "$name is down"
    fi
fi
