#!/bin/bash
# find /dir/path -maxdepth 0 -type d -empty
if [[ $(ls -A /media/liren/WD_Ext4) ]]; then
    tmux new-session -s sync 'rsync -av --stats --progress -h --delete ~/ /media/liren/WD_Ext4/home_backup/ --exclude-from=/home/liren/bin/exclude.list'
    # exclude-from don't accept relative path. don't use include-from.
    # ".*" & "*./" exclude everything hidden
else
    echo "Error: WD_Ext4 is not mounted."
fi
exit 0
